[project]
name = "virtual-hand-clone"
version = "0.1.0"
description = "A virtual hand clone application using MediaPipe and OpenCV."
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = ["mediapipe>=0.10.21", "opencv-python>=4.11.0.86"]

[dependency-groups]
dev = ["ruff>=0.14.5"]
